apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deployment
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 2
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: game
          image: josedocker22/books:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  type: NodePort
  selector:
    run: load-balancer-example
  ports:
    - targetPort: 8080
      port: 8101
      nodePort: 30002